name: LintWithBlack

on:
  workflow_dispatch:
#  push:
#    branches: ["main", "master"]
#  pull_request:
#    branches: ["main", "master"]

jobs:
  lintwithblack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable